//! Turning a hostile message body into HTML that is safe to render.
//!
//! This is one of the two genuinely hard parts of Mach (see
//! `docs/superpowers/specs/`): message bodies are arbitrary HTML written by
//! strangers, and they are rendered in a WebView inside a desktop app that
//! holds five accounts' mail.
//!
//! The pipeline is:
//!
//! 1. [`quotes`] splits the raw body into new content and quoted history. This
//!    runs first because every quote signal lives in markup the sanitizer
//!    removes. It is not a security boundary — see the module docs.
//! 2. [`sanitize`] cleans each half independently against an explicit
//!    allowlist, blocks remote images, and forces link safety.
//!
//! Both halves come back sanitized, so a caller cannot accidentally render the
//! raw quote.
//!
//! # What this module does *not* defend against
//!
//! Sanitizing is necessary and not sufficient. The WebView layer must also:
//!
//! * render the body in a **sandboxed iframe** (`allow-same-origin
//!   allow-popups` — never `allow-scripts`, and never `allow-same-origin`
//!   together with `allow-scripts`);
//! * serve it under a **Content-Security-Policy** of at least
//!   `default-src 'none'; img-src data: <attachment scheme>; style-src
//!   'unsafe-inline'; form-action 'none'; frame-src 'none'; script-src 'none';
//!   base-uri 'none'`, widened to allow `https:` images only while the user has
//!   opted in;
//! * intercept navigation and open links in the system browser rather than
//!   letting the WebView navigate — at the navigation layer
//!   (`ipc::render::link_guard`), because a click listener inside a
//!   scripting-disabled frame never runs in WebKit;
//! * run rendering off the UI thread, since a pathological body costs CPU.

pub mod entities;
pub mod flowed;
pub mod quotes;
pub mod sanitize;
pub mod text;

use serde::Serialize;

pub use flowed::{flowed_params, unflow};
pub use quotes::Split;
pub use sanitize::{sanitize_fragment, text_to_html, ImageCounts};

/// Everything the UI needs to render one message body.
#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RenderedBody {
    /// Safe HTML for the new content.
    pub html: String,
    /// Safe HTML for the quoted history. Empty when there is none.
    pub quoted_html: String,
    /// Whether quoted history was found, i.e. whether to offer "show quoted
    /// text".
    pub has_quoted: bool,
    /// Remote images deferred behind "load images", across both halves. Only
    /// non-zero when the caller asked for every remote image to be blocked.
    pub blocked_remote_images: usize,
    /// Images dropped as tracking pixels, across both halves. Drives the
    /// "N trackers blocked" line, which — unlike the old one — is not offering
    /// to load anything.
    pub blocked_trackers: usize,
    /// `cid:` references the UI must resolve against this message's parts.
    pub inline_cid_images: usize,
    /// Accepted inline `data:` raster images.
    pub inline_data_images: usize,
}

/// Per-render choices the user can make.
#[derive(Debug, Clone, Copy, Default)]
pub struct RenderOptions {
    /// Set once the user has clicked "load remote images" for this message or
    /// sender. Affects images and nothing else.
    pub allow_remote_images: bool,
    /// The sender declared `Content-Type: text/plain; format=flowed`, so the
    /// line breaks that end in a space are theirs to undo — see [`flowed`].
    /// Never inferred from the body: a `false` here means "we were not told",
    /// and a body we were not told about keeps every break it arrived with.
    pub text_flowed: bool,
    /// `delsp=yes` alongside it. Meaningless without `text_flowed`.
    pub text_delsp: bool,
}

/// Render a `text/html` body with remote images blocked.
pub fn render_html(raw: &str) -> RenderedBody {
    render_html_with(raw, RenderOptions::default())
}

pub fn render_html_with(raw: &str, opts: RenderOptions) -> RenderedBody {
    let split = quotes::split_html(raw);
    let mut counts = ImageCounts::default();

    let (html, new_counts) = sanitize_fragment(&split.new, opts.allow_remote_images);
    counts.add(new_counts);

    let quoted_html = match &split.quoted {
        Some(quoted) => {
            let (html, quoted_counts) = sanitize_fragment(quoted, opts.allow_remote_images);
            counts.add(quoted_counts);
            html
        }
        None => String::new(),
    };

    RenderedBody {
        html,
        quoted_html,
        has_quoted: split.quoted.is_some(),
        blocked_remote_images: counts.blocked_remote,
        blocked_trackers: counts.blocked_trackers,
        inline_cid_images: counts.inline_cid,
        inline_data_images: counts.inline_data,
    }
}

/// Render a `text/plain` body. Output is generated by us rather than cleaned,
/// so it does not go through the HTML sanitizer.
pub fn render_text(raw: &str) -> RenderedBody {
    render_text_with(raw, RenderOptions::default())
}

/// # Why the flowed pass runs before the quote split
///
/// [`flowed::unflow`] is the decoder for the body: until it has run, the line
/// breaks in a `format=flowed` message are a mix of the sender's and their
/// generator's, and a quote is a run of lines at one depth rather than the
/// lines as they arrived. Decoding first hands [`quotes::split_text`] the text
/// the sender actually wrote, with the `>` prefixes still on it.
pub fn render_text_with(raw: &str, opts: RenderOptions) -> RenderedBody {
    // Truncated here rather than only in `text_to_html`, so the flowed pass and
    // the quote split are both bounded by the same limit the sanitizer is.
    let bounded = sanitize::truncate_on_char_boundary(raw, sanitize::MAX_INPUT_BYTES);
    let decoded;
    let raw: &str = if opts.text_flowed {
        decoded = flowed::unflow(&bounded, opts.text_delsp);
        &decoded
    } else {
        &bounded
    };
    let split = quotes::split_text(raw);
    RenderedBody {
        html: text_to_html(&split.new),
        quoted_html: split.quoted.as_deref().map(text_to_html).unwrap_or_default(),
        has_quoted: split.quoted.is_some(),
        ..Default::default()
    }
}
