//! Composing and sending mail — the switch point.
//!
//! Gmail has no structured send. `users.messages.send` takes one field, `raw`,
//! holding a complete RFC822 message in base64url. Everything a reply needs to
//! thread correctly in *somebody else's* client — `In-Reply-To`, `References`,
//! a `Re:` that has not stacked, an RFC 2047 encoded subject — has to be right
//! in those bytes, because nothing downstream will fix it. That is why this is
//! a module with tests over the generated bytes rather than a function that
//! calls a builder.
//!
//! # Layout
//!
//! | module | what lives there |
//! |---|---|
//! | [`address`] | recipient arithmetic: reply-all, dedupe, exclude self |
//! | [`markdown`] | the markdown-ish editor grammar → clean HTML |
//! | [`mime`] | [`Outgoing`] → RFC822 bytes |
//! | [`draft`] | drafts, autosave, and building a reply from a stored thread |
//! | [`outbox`] | the ten-second undo window and the durable send queue |
//!
//! # Three decisions worth knowing
//!
//! **Address headers are rendered here, not by `mail-builder`.** The crate
//! builds the message structure, the body encoding and every other header, but
//! its `rfc2047_encode` wraps an encoded display name in double quotes —
//! `"=?utf-8?B?Sm9zw6k=?=" <jose@…>` — and RFC 2047 §5 forbids encoded-words
//! inside a quoted-string. Most clients decode it anyway; "most" is not the bar
//! for the header that carries your name into other people's inboxes. See
//! [`mime::render_mailboxes`].
//!
//! **The outbox is a table, not a timer.** A ten-second undo window implemented
//! as a `setTimeout` loses the message if the window closes inside it. Here the
//! finished RFC822 bytes are committed to SQLite *before* the window opens, so
//! the only thing the timer decides is when a durable row is allowed to leave.
//! Undo deletes the row; a crash leaves it, and the next flush sends it.
//!
//! **This module owns its own tables.** `db::schema` belongs to another unit,
//! so [`ensure_compose_schema`] creates `compose_drafts` and `compose_outbox`
//! with `CREATE TABLE IF NOT EXISTS`, exactly as
//! [`command_queries::ensure_command_schema`](crate::db::command_queries::ensure_command_schema)
//! does for `snoozed_threads`. Promoting them into `MIGRATIONS` later is a
//! no-op for this call.

pub mod address;
pub mod draft;
pub mod markdown;
pub mod mime;
pub mod mirror;
pub mod outbox;
pub mod remote;

use rusqlite::Connection;

use crate::commands::CommandError;
use crate::db::{DbError, Result as DbResult};
use crate::google::GoogleError;

pub use address::{dedupe, reply_recipients, Recipients};
pub use draft::{
    delete_draft, load_draft, load_draft_for_thread, prepare, save_draft, Draft, DraftKind,
    DraftRemote, RemoteState, ReplyContext,
};
pub use remote::DraftRemoteSync;
pub use mime::{build_rfc822, Mailbox, Outgoing};
pub use outbox::{Outbox, OutboxEntry, OutboxState, UNDO_WINDOW_MS};

// ---------------------------------------------------------------------------
// schema
// ---------------------------------------------------------------------------

/// What you are still typing, and what has not left yet.
///
/// `compose_outbox.rfc822` holds the finished message. Storing the bytes rather
/// than the draft fields is what makes the undo window safe: once the row is
/// committed, sending it needs no part of the UI to still exist, so closing the
/// window mid-window delays the send instead of losing it.
///
/// `compose_drafts` used to be local-only, and that was the bug: a draft the
/// agent wrote existed in this table, in this Mac, and nowhere a person would
/// look. It now carries the three ids that tie it to a real Gmail draft — see
/// [`DRAFT_REMOTE_COLUMNS`] and [`remote`].
pub const COMPOSE_SCHEMA: &str = r#"
CREATE TABLE IF NOT EXISTS compose_drafts (
    id            TEXT    PRIMARY KEY,
    account_id    INTEGER NOT NULL,
    -- The local thread row being replied to; NULL for a fresh message.
    thread_id     INTEGER,
    -- The local message row being replied to, so threading headers survive a
    -- restart along with the text.
    reply_to_id   INTEGER,
    kind          TEXT    NOT NULL DEFAULT 'new',
    to_json       TEXT    NOT NULL DEFAULT '[]',
    cc_json       TEXT    NOT NULL DEFAULT '[]',
    bcc_json      TEXT    NOT NULL DEFAULT '[]',
    subject       TEXT    NOT NULL DEFAULT '',
    -- The markdown-ish source, never the rendered HTML: the editor round-trips
    -- what the user typed, and HTML is produced once, at send.
    body          TEXT    NOT NULL DEFAULT '',
    updated_at    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_compose_drafts_thread ON compose_drafts (thread_id);

CREATE TABLE IF NOT EXISTS compose_outbox (
    id              TEXT    PRIMARY KEY,
    account_id      INTEGER NOT NULL,
    thread_id       INTEGER,
    gmail_thread_id TEXT,
    subject         TEXT    NOT NULL DEFAULT '',
    -- The complete RFC822 message. Already built; the flusher only encodes it.
    rfc822          BLOB    NOT NULL,
    -- holding | sending | sent | failed
    state           TEXT    NOT NULL DEFAULT 'holding',
    -- Unix millis. Nothing leaves before this; the undo window is now + 10s and
    -- a scheduled send is whatever the user picked.
    send_after      INTEGER NOT NULL,
    created_at      INTEGER NOT NULL DEFAULT 0,
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    -- The Gmail message id once it has landed.
    sent_message_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_compose_outbox_due ON compose_outbox (state, send_after);
"#;

/// The columns that tie a local draft to the Gmail draft it was pushed to.
///
/// Added here rather than as a numbered migration for the same reason the
/// tables themselves are: this module owns them, and `db::schema` cannot create
/// a column on a table it does not know exists. An `ALTER TABLE … ADD COLUMN`
/// in a migration would fail outright on a store whose composer had never run.
/// Adding them from here is idempotent in both directions — a fresh database
/// and a database written by yesterday's build end up identical.
///
///  * `gmail_draft_id` — what `drafts.update` and `drafts.delete` address. Its
///    presence is also the answer to "has this ever reached Google".
///  * `gmail_message_id` / `gmail_thread_id` — the ordinary message and thread
///    ids Gmail filed the draft under. These are what stop one draft becoming
///    two: the local mirror row adopts them, so the sync pass that later sees
///    this draft upserts *onto* Mach's row instead of inserting beside it.
///  * `remote_state` — `pending`, `synced` or `failed`. A draft is never
///    silently local-only; `failed` is what the composer says out loud.
const DRAFT_REMOTE_COLUMNS: &[(&str, &str)] = &[
    ("gmail_draft_id", "TEXT"),
    ("gmail_message_id", "TEXT"),
    ("gmail_thread_id", "TEXT"),
    ("remote_state", "TEXT NOT NULL DEFAULT 'pending'"),
    ("remote_error", "TEXT"),
    ("remote_synced_at", "INTEGER NOT NULL DEFAULT 0"),
];

/// Idempotent. Called by every entry point into this module, so no caller has
/// to remember it.
pub fn ensure_compose_schema(conn: &Connection) -> DbResult<()> {
    conn.execute_batch(COMPOSE_SCHEMA)?;
    add_missing_columns(conn, "compose_drafts", DRAFT_REMOTE_COLUMNS)?;
    Ok(())
}

/// `ALTER TABLE … ADD COLUMN` for whatever is not there yet.
///
/// SQLite has no `ADD COLUMN IF NOT EXISTS`, and a failed `ALTER` inside the
/// caller's transaction would take the rest of the batch down with it, so the
/// existing columns are read first.
fn add_missing_columns(
    conn: &Connection,
    table: &str,
    columns: &[(&str, &str)],
) -> DbResult<()> {
    let mut stmt = conn.prepare(&format!("PRAGMA table_info({table})"))?;
    let existing: Vec<String> = stmt
        .query_map([], |row| row.get::<_, String>(1))?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    drop(stmt);
    for (name, ty) in columns {
        if existing.iter().any(|c| c == name) {
            continue;
        }
        conn.execute_batch(&format!("ALTER TABLE {table} ADD COLUMN {name} {ty};"))?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// errors
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error)]
pub enum ComposeError {
    #[error("{0}")]
    Invalid(String),

    #[error("no thread with id {0} in the local store")]
    UnknownThread(i64),

    #[error("no account with id {0} in the local store")]
    UnknownAccount(i64),

    #[error("no message with id {0} in the local store")]
    UnknownMessage(i64),

    #[error("nothing in the outbox with id {0}")]
    UnknownOutbox(String),

    #[error("could not build the message: {0}")]
    Mime(String),

    #[error("local store: {0}")]
    Db(#[from] DbError),

    #[error("gmail: {0}")]
    Google(#[from] GoogleError),

    #[error(transparent)]
    Command(#[from] CommandError),
}

impl ComposeError {
    pub fn invalid(message: impl Into<String>) -> Self {
        ComposeError::Invalid(message.into())
    }

    /// The stable tag the frontend branches on.
    pub fn kind(&self) -> &'static str {
        match self {
            ComposeError::Invalid(_) => "invalid",
            ComposeError::UnknownThread(_) => "unknownThread",
            ComposeError::UnknownAccount(_) => "unknownAccount",
            ComposeError::UnknownMessage(_) => "unknownMessage",
            ComposeError::UnknownOutbox(_) => "unknownOutbox",
            ComposeError::Mime(_) => "mime",
            ComposeError::Db(_) => "db",
            ComposeError::Google(_) => "google",
            ComposeError::Command(inner) => inner.kind(),
        }
    }
}

pub type Result<T> = std::result::Result<T, ComposeError>;
