//! Composing and sending mail — the switch point.
//!
//! Gmail has no structured send. `users.messages.send` takes one field, `raw`,
//! holding a complete RFC822 message in base64url. Everything a reply needs to
//! thread correctly in *somebody else's* client — `In-Reply-To`, `References`,
//! a `Re:` that has not stacked, an RFC 2047 encoded subject — has to be right
//! in those bytes, because nothing downstream will fix it. That is why this is
//! a module with tests over the generated bytes rather than a function that
//! calls a builder.
//!
//! # Layout
//!
//! | module | what lives there |
//! |---|---|
//! | [`address`] | recipient arithmetic: reply-all, dedupe, exclude self |
//! | [`markdown`] | the markdown-ish editor grammar → clean HTML |
//! | [`mime`] | [`Outgoing`] → RFC822 bytes |
//! | [`draft`] | drafts, autosave, and building a reply from a stored thread |
//! | [`outbox`] | the ten-second undo window and the durable send queue |
//!
//! # Three decisions worth knowing
//!
//! **Address headers are rendered here, not by `mail-builder`.** The crate
//! builds the message structure, the body encoding and every other header, but
//! its `rfc2047_encode` wraps an encoded display name in double quotes —
//! `"=?utf-8?B?Sm9zw6k=?=" <jose@…>` — and RFC 2047 §5 forbids encoded-words
//! inside a quoted-string. Most clients decode it anyway; "most" is not the bar
//! for the header that carries your name into other people's inboxes. See
//! [`mime::render_mailboxes`].
//!
//! **The outbox is a table, not a timer.** A ten-second undo window implemented
//! as a `setTimeout` loses the message if the window closes inside it. Here the
//! finished RFC822 bytes are committed to SQLite *before* the window opens, so
//! the only thing the timer decides is when a durable row is allowed to leave.
//! Undo deletes the row; a crash leaves it, and the next flush sends it.
//!
//! **This module owns its own tables.** `db::schema` belongs to another unit,
//! so [`ensure_compose_schema`] creates `compose_drafts` and `compose_outbox`
//! with `CREATE TABLE IF NOT EXISTS`, exactly as
//! [`command_queries::ensure_command_schema`](crate::db::command_queries::ensure_command_schema)
//! does for `snoozed_threads`. Promoting them into `MIGRATIONS` later is a
//! no-op for this call.

pub mod address;
pub mod attach;
pub mod draft;
pub mod forward;
pub mod html;
pub mod markdown;
pub mod mime;
pub mod mirror;
pub mod outbox;
pub mod remote;

use rusqlite::Connection;

use crate::commands::CommandError;
use crate::db::{DbError, Result as DbResult};
use crate::google::GoogleError;

pub use address::{dedupe, reply_recipients, Recipients};
pub use attach::{Attachment, MAX_ATTACHMENT_BYTES, MAX_TOTAL_ATTACHMENT_BYTES};
pub use draft::{
    delete_draft, load_draft, load_draft_for_thread, prepare, save_draft, BodyFormat, Draft,
    DraftKind, DraftRemote, RemoteState, ReplyContext,
};
pub use remote::DraftRemoteSync;
pub use mime::{build_rfc822, Mailbox, Outgoing, OutgoingAttachment};
pub use outbox::{Outbox, OutboxEntry, OutboxState, UNDO_WINDOW_MS};

// ---------------------------------------------------------------------------
// schema
// ---------------------------------------------------------------------------

/// What you are still typing, and what has not left yet.
///
/// `compose_outbox.rfc822` holds the finished message. Storing the bytes rather
/// than the draft fields is what makes the undo window safe: once the row is
/// committed, sending it needs no part of the UI to still exist, so closing the
/// window mid-window delays the send instead of losing it.
///
/// `compose_drafts` used to be local-only, and that was the bug: a draft the
/// agent wrote existed in this table, in this Mac, and nowhere a person would
/// look. It now carries the three ids that tie it to a real Gmail draft — see
/// [`DRAFT_REMOTE_COLUMNS`] and [`remote`].
pub const COMPOSE_SCHEMA: &str = r#"
CREATE TABLE IF NOT EXISTS compose_drafts (
    id            TEXT    PRIMARY KEY,
    account_id    INTEGER NOT NULL,
    -- The local thread row being replied to; NULL for a fresh message.
    thread_id     INTEGER,
    -- The local message row being replied to, so threading headers survive a
    -- restart along with the text.
    reply_to_id   INTEGER,
    kind          TEXT    NOT NULL DEFAULT 'new',
    to_json       TEXT    NOT NULL DEFAULT '[]',
    cc_json       TEXT    NOT NULL DEFAULT '[]',
    bcc_json      TEXT    NOT NULL DEFAULT '[]',
    subject       TEXT    NOT NULL DEFAULT '',
    -- The markdown-ish source, never the rendered HTML: the editor round-trips
    -- what the user typed, and HTML is produced once, at send.
    body          TEXT    NOT NULL DEFAULT '',
    updated_at    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_compose_drafts_thread ON compose_drafts (thread_id);

CREATE TABLE IF NOT EXISTS compose_outbox (
    id              TEXT    PRIMARY KEY,
    account_id      INTEGER NOT NULL,
    thread_id       INTEGER,
    gmail_thread_id TEXT,
    subject         TEXT    NOT NULL DEFAULT '',
    -- The complete RFC822 message. Already built; the flusher only encodes it.
    rfc822          BLOB    NOT NULL,
    -- holding | sending | sent | failed
    state           TEXT    NOT NULL DEFAULT 'holding',
    -- Unix millis. Nothing leaves before this; the undo window is now + 10s and
    -- a scheduled send is whatever the user picked.
    send_after      INTEGER NOT NULL,
    created_at      INTEGER NOT NULL DEFAULT 0,
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    -- The Gmail message id once it has landed.
    sent_message_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_compose_outbox_due ON compose_outbox (state, send_after);

-- Drafts that have stopped existing, and roughly when.
--
-- A tombstone rather than nothing, because the composer's autosave can be in
-- flight at the moment the draft is sent or thrown away, and a save that lands
-- half a second later would otherwise write the row straight back — and the
-- push behind it would `drafts.create` a Gmail draft holding the text of a
-- message the owner has already sent. That is the shape of the duplicate he
-- found in his mailbox: an outbox row, a sent message, and a draft of the same
-- words created thirteen milliseconds after `⌘⏎`.
--
-- The Gmail identity travels with the tombstone so that undoing a send can put
-- it back: the recalled draft has to keep pointing at the Gmail draft it came
-- from, or the next save creates a second one.
--
-- Rows are swept with the delivered outbox rows, a day later.
CREATE TABLE IF NOT EXISTS compose_retired_drafts (
    id               TEXT    PRIMARY KEY,
    account_id       INTEGER NOT NULL DEFAULT 0,
    thread_id        INTEGER,
    gmail_draft_id   TEXT,
    gmail_message_id TEXT,
    gmail_thread_id  TEXT,
    retired_at       INTEGER NOT NULL DEFAULT 0
);

-- Files waiting to go out with a draft.
--
-- The bytes are a BLOB rather than a path for the same reason
-- `compose_outbox.rfc822` is: a draft that references a file the owner has
-- since moved, renamed or deleted is a send that fails at the last moment, and
-- the whole point of the outbox is that once a message is queued nothing
-- outside the store can stop it. It also means one delete statement takes an
-- abandoned draft's files with it, with no orphan directory to sweep.
CREATE TABLE IF NOT EXISTS compose_attachments (
    id         TEXT    PRIMARY KEY,
    draft_id   TEXT    NOT NULL,
    -- Already through `attachments::names::safe_filename`. This is the name the
    -- recipient sees, so it is also the name shown in the composer.
    filename   TEXT    NOT NULL,
    mime_type  TEXT    NOT NULL DEFAULT 'application/octet-stream',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    bytes      BLOB    NOT NULL,
    added_at   INTEGER NOT NULL DEFAULT 0,
    -- In the body rather than beside it. See `ATTACHMENT_INLINE_COLUMNS`, which
    -- adds both of these to a table written before they existed.
    inline     INTEGER NOT NULL DEFAULT 0,
    content_id TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_compose_attachments_draft ON compose_attachments (draft_id);
"#;

/// The columns that tie a local draft to the Gmail draft it was pushed to.
///
/// Added here rather than as a numbered migration for the same reason the
/// tables themselves are: this module owns them, and `db::schema` cannot create
/// a column on a table it does not know exists. An `ALTER TABLE … ADD COLUMN`
/// in a migration would fail outright on a store whose composer had never run.
/// Adding them from here is idempotent in both directions — a fresh database
/// and a database written by yesterday's build end up identical.
///
///  * `gmail_draft_id` — what `drafts.update` and `drafts.delete` address. Its
///    presence is also the answer to "has this ever reached Google".
///  * `gmail_message_id` / `gmail_thread_id` — the ordinary message and thread
///    ids Gmail filed the draft under. These are what stop one draft becoming
///    two: the local mirror row adopts them, so the sync pass that later sees
///    this draft upserts *onto* Mach's row instead of inserting beside it.
///  * `remote_state` — `pending`, `synced` or `failed`. A draft is never
///    silently local-only; `failed` is what the composer says out loud.
///  * `body_format` — `markdown` or `html`. The default is `markdown` and it is
///    load-bearing: every row written before the editor became a rich-text one
///    holds markdown-ish source, and reading it as HTML would show the owner his
///    own asterisks and send a message with none of the emphasis he asked for.
///    See [`draft::BodyFormat`].
const DRAFT_REMOTE_COLUMNS: &[(&str, &str)] = &[
    ("gmail_draft_id", "TEXT"),
    ("gmail_message_id", "TEXT"),
    ("gmail_thread_id", "TEXT"),
    ("remote_state", "TEXT NOT NULL DEFAULT 'pending'"),
    ("remote_error", "TEXT"),
    ("remote_synced_at", "INTEGER NOT NULL DEFAULT 0"),
    ("body_format", "TEXT NOT NULL DEFAULT 'markdown'"),
];

/// The columns that tie a queued message back to the draft it was written as.
///
/// Added the same way, and for the same reason, as [`DRAFT_REMOTE_COLUMNS`]:
/// this module owns the table, and a store written by yesterday's build has to
/// end up identical to a fresh one.
///
///  * `draft_id` — the local `compose_drafts` row. What undo revives, and what
///    the mirror was filed under before Gmail had heard of it.
///  * `gmail_draft_id` — present exactly when a real Gmail draft is behind this
///    message. **This is what decides `drafts.send` against `messages.send`**,
///    and it is read at flush rather than at queue because the draft row is
///    gone by then: the identity has to be carried, not looked up.
///  * `gmail_draft_message_id` — the message Gmail filed that draft under. Only
///    used to recognise a mirror a sync pass re-imported during the undo
///    window, which must not survive the send.
const OUTBOX_DRAFT_COLUMNS: &[(&str, &str)] = &[
    ("draft_id", "TEXT"),
    ("gmail_draft_id", "TEXT"),
    ("gmail_draft_message_id", "TEXT"),
];

/// What tells a file in the body from a file beside it.
///
/// Added the same way as the two lists above. Both default to the shape every
/// row written before them had — not inline, no `Content-ID` — so a store from
/// yesterday's build sends exactly the messages it did yesterday.
///
///  * `inline` — `Content-Disposition: inline` and an `<img src="cid:…">` in
///    the body, rather than a file listed under the message.
///  * `content_id` — the `cid:` the body points at. Allocated for every
///    attachment so that turning one inline is a flag rather than a rename;
///    see [`attach::Attachment::content_id`].
const ATTACHMENT_INLINE_COLUMNS: &[(&str, &str)] = &[
    ("inline", "INTEGER NOT NULL DEFAULT 0"),
    ("content_id", "TEXT NOT NULL DEFAULT ''"),
];

/// Idempotent. Called by every entry point into this module, so no caller has
/// to remember it.
pub fn ensure_compose_schema(conn: &Connection) -> DbResult<()> {
    conn.execute_batch(COMPOSE_SCHEMA)?;
    add_missing_columns(conn, "compose_drafts", DRAFT_REMOTE_COLUMNS)?;
    add_missing_columns(conn, "compose_outbox", OUTBOX_DRAFT_COLUMNS)?;
    add_missing_columns(conn, "compose_attachments", ATTACHMENT_INLINE_COLUMNS)?;
    Ok(())
}

/// `ALTER TABLE … ADD COLUMN` for whatever is not there yet.
///
/// SQLite has no `ADD COLUMN IF NOT EXISTS`, and a failed `ALTER` inside the
/// caller's transaction would take the rest of the batch down with it, so the
/// existing columns are read first.
fn add_missing_columns(
    conn: &Connection,
    table: &str,
    columns: &[(&str, &str)],
) -> DbResult<()> {
    let mut stmt = conn.prepare(&format!("PRAGMA table_info({table})"))?;
    let existing: Vec<String> = stmt
        .query_map([], |row| row.get::<_, String>(1))?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    drop(stmt);
    for (name, ty) in columns {
        if existing.iter().any(|c| c == name) {
            continue;
        }
        conn.execute_batch(&format!("ALTER TABLE {table} ADD COLUMN {name} {ty};"))?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// errors
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error)]
pub enum ComposeError {
    #[error("{0}")]
    Invalid(String),

    #[error("no thread with id {0} in the local store")]
    UnknownThread(i64),

    #[error("no account with id {0} in the local store")]
    UnknownAccount(i64),

    #[error("no message with id {0} in the local store")]
    UnknownMessage(i64),

    #[error("nothing in the outbox with id {0}")]
    UnknownOutbox(String),

    #[error("could not build the message: {0}")]
    Mime(String),

    #[error("local store: {0}")]
    Db(#[from] DbError),

    #[error("gmail: {0}")]
    Google(#[from] GoogleError),

    #[error(transparent)]
    Command(#[from] CommandError),
}

impl ComposeError {
    pub fn invalid(message: impl Into<String>) -> Self {
        ComposeError::Invalid(message.into())
    }

    /// The stable tag the frontend branches on.
    pub fn kind(&self) -> &'static str {
        match self {
            ComposeError::Invalid(_) => "invalid",
            ComposeError::UnknownThread(_) => "unknownThread",
            ComposeError::UnknownAccount(_) => "unknownAccount",
            ComposeError::UnknownMessage(_) => "unknownMessage",
            ComposeError::UnknownOutbox(_) => "unknownOutbox",
            ComposeError::Mime(_) => "mime",
            ComposeError::Db(_) => "db",
            ComposeError::Google(_) => "google",
            ComposeError::Command(inner) => inner.kind(),
        }
    }
}

pub type Result<T> = std::result::Result<T, ComposeError>;
